/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'anx00283' at '2/27/17 1:47 PM' with Gradle 2.11
 *
 * @author anx00283, @date 2/27/17 1:47 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
